/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicioSesion;

/**
 *
 * @author Administrator
 */
public class LoginIncorrecto extends javax.swing.JFrame {

    /**
     * Creates new form LoginIncorrecto
     */
    public LoginIncorrecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facebook = new javax.swing.JLabel();
        registrate = new javax.swing.JTextField();
        azul = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        no_cerrar_sesion = new javax.swing.JCheckBox();
        pon_contraseña = new javax.swing.JTextField();
        pon_correo = new javax.swing.JTextField();
        entrar = new javax.swing.JTextField();
        o_registrate = new javax.swing.JTextField();
        has_olvidado = new javax.swing.JTextField();
        inicio_sesion = new javax.swing.JTextField();
        border = new javax.swing.JLabel();
        blanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        facebook.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        facebook.setForeground(new java.awt.Color(255, 255, 255));
        facebook.setText("facebook");
        getContentPane().add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 58));

        registrate.setBackground(new java.awt.Color(51, 204, 0));
        registrate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrate.setForeground(new java.awt.Color(255, 255, 255));
        registrate.setText("Registrarte");
        getContentPane().add(registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, -1));

        azul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDO_FACEBOOK.jpeg"))); // NOI18N
        getContentPane().add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        jTextField1.setText("Contraseña:");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, 30));

        jTextField2.setText("Correo  electrónico: ");
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 130, 30));

        no_cerrar_sesion.setText("No cerrar sesión");
        no_cerrar_sesion.setBorder(null);
        getContentPane().add(no_cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        getContentPane().add(pon_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 210, -1));
        getContentPane().add(pon_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, -1));

        entrar.setBackground(new java.awt.Color(0, 153, 255));
        entrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("Entrar");
        getContentPane().add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 60, 30));

        o_registrate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        o_registrate.setForeground(new java.awt.Color(0, 102, 204));
        o_registrate.setText("o Regístrate en Facebook");
        o_registrate.setBorder(null);
        getContentPane().add(o_registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 150, -1));

        has_olvidado.setForeground(new java.awt.Color(0, 102, 204));
        has_olvidado.setText("¿Has olvidado la contraseña?");
        has_olvidado.setBorder(null);
        getContentPane().add(has_olvidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        inicio_sesion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inicio_sesion.setText("Inicio de sesión con Facebook ");
        inicio_sesion.setBorder(null);
        getContentPane().add(inicio_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 230, -1));

        border.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 380, -1));

        blanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 450, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginIncorrecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginIncorrecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginIncorrecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginIncorrecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginIncorrecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel azul;
    private javax.swing.JLabel blanco;
    private javax.swing.JLabel border;
    private javax.swing.JTextField entrar;
    private javax.swing.JLabel facebook;
    private javax.swing.JTextField has_olvidado;
    private javax.swing.JTextField inicio_sesion;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox no_cerrar_sesion;
    private javax.swing.JTextField o_registrate;
    private javax.swing.JTextField pon_contraseña;
    private javax.swing.JTextField pon_correo;
    private javax.swing.JTextField registrate;
    // End of variables declaration//GEN-END:variables
}
